### PR TITLE
New definitions needed for the LES branch

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by yglukhov** [comment]
It's concerning how `eth_common` gains more protocol specific type definitions, and the trie dependencies, which I would not consider that "common".

**Comment by zah** [comment]
I would say it gains blockchain-related definitions. The guiding principle for me was that these objects and algorithms are ultimately described in the Yellow Paper, so they are not subject to implementation details (in the same way `AbstractChainDb` and `TrieDatabaseRef` are). `eth_common` defines only such well-defined algorithms that are guaranteed to never change.

**Comment by yglukhov** [comment]
That's one way to think of it. But you could say EVM is well defined by the yellow paper, but it's not here. So where's the boundary? :)

**Comment by zah** [comment]
I wouldn't argue too much about this, as obviously the process was a bit more ad-hoc with me extending the `AbstractChainDb` interface whenever I needed, but if I have to draw a boundary, let me give it a try. 

The yellow paper describes the bitwise representation of certain things - the RLP format and then the Trie structure based on this format which must be bit-for-bit identical in each implementation. Other types such as Account, Transaction, etc, must also be bit-for-bit identical, because their hashes are used in the consensus protocol. That's why I consider them reasonable to include in `eth_common`.  Admittedly, the trie proofs are in a bit more gray category because they specify a specific packaging format for the bit-for-bit identical data, but perhaps I'll be able to remove them from `eth_common` in the future.

A type such as `BaseVMState` is not in the same category - there are many ways to implement the EVM internals.

**Comment by yglukhov** [comment]
I'm OK with merging it now. But generally I think we should tend to not let anything into eth_common unless it is common to nimbus and eth_p2p. I hope we'll revisit it again, or maybe even merge nimbus+p2p+eth_common, who knows...

Btw, `{.base.}` pragmas are still missing :)

**Comment by arnetheduck** [comment]
tends to be a bit of a code smell when you end up with these big bins of unrelated types - makes you wonder if the architecture could do with a refactoring pass.. likewise for having `types.nim` where things are mixed up simply because no clean separation was found between them on first inspection.

**Comment by zah** [comment]
@arnetheduck, I think you haven't experienced the `types` module problem in Nim enough to appreciate it. I've now explained it in a bit more detail in the forum thread that started the recent discussions:

https://forum.nim-lang.org/t/4293#26876

**Pull request merged**
